### ISSUE TITLE
When working with large data array in example.py, "for item in data:" loop is taking very long. Any workaround to this?

### ISSUE THREAD

**Issue by oemertekin** [Samuel-Maddock/pure-LDP#6]
I am currently trying some things out where my array has a lot of entries (more than a million). I think in the example that you @Samuel-Maddock used, you had around 18,000 entries in your data array. Any suggestion on how to speed the for loop up?

**Comment by Samuel-Maddock** [comment]
For large datasets this will take a while, but it shouldn't be unreasonably long - But it is heavily dependent on the frequency oracle used and the size of your domain (number of possible values a "user" could have).

Which frequency oracle are you trying, what is the exact size of the dataset and what is the size of the domain?

**Comment by oemertekin** [comment]
I am using the OLH frequency oracle for now. Haven't tried the other one's out yet. Domain size would be 266 and size of the data array (vector) would be 1139469767. Are the other frequency oracles faster with the given sizes?

**Comment by Samuel-Maddock** [comment]
OLH is slow for very large d (domain size), but it shouldn't struggle for d=266. The main issue is that you are trying to privatise a dataset with 1 billion entries. This will be slow and there is no way to avoid this for loop issue when running on a single machine. Perhaps you can work with a slightly smaller subset of your data (in the millions) if speed is the issue?

In practical deployments, this is often the size of dataset that is expected - and is needed to give good estimations. However, in practical deployments LDP is run on something like the client-server model, where each user would privatise a single item themselves (which takes <1s) and the computation cost would effectively be spread across a billion devices (i.e mobile phones). The server would then aggregate each entry and calculate estimations. 

When working on a single machine, you have the possibility of trying to parallelise a python for-loop to run across multiple cores of your machine i.e using multiprocessing or pathos. In terms of more practical deployments, you would probably work with something like Hadoop and MapReduce to speed this up.

**Comment by oemertekin** [comment]
Thanks @Samuel-Maddock! I will try to work with subsets and see how this goes.

**Comment by oemertekin** [comment]
@Samuel-Maddock is there a way to get a time estimate of some sort to see how long the code execution will aproximately take? Ideally something that works in jupyter notebook as well.

**Comment by Samuel-Maddock** [comment]
I suppose I could work on something like this natively built into the library. I think it would be something like:

1. Run .privatise() say 10 times and average the client-side time
2. Run .aggregate() and .estimate() say 10 times and average the server-side time
3. Extrapolate the times for the size of the whole dataset

This would be a very rough estimate. This is something you can do yourself now though, for example take a subset of your data (say n=1000) and time it for both client and server and then scale it for n=1 million, 1 billion etc

Are you still experiencing time issues for n=1 million?

**Comment by oemertekin** [comment]
It works quite well for n=1 million. I was able to come up with a feasible method to track execution time as well. Do you think it's an option to use python's multiprocessing library for the privatisation/aggregation for loop? In order to speed up that loop.

**Comment by Samuel-Maddock** [comment]
It's good to know that the method tracks execution time well. When I get some time I will work on adding this to the library. 

I have some (but limited) experience with multiprocessing, and perhaps it would be feasible but I don't know if you will experience massive speed ups - would depend on the number of cores in your machine. If you do go ahead and try it, I would be interested in hearing your results. 

For the server-side, I could see an implementation using multiprocessing being of use in the ```aggregate_all()``` and ```estimate_all()``` methods since at the moment these are just simple for loops. If multiprocessing works for you, then I might consider implementing it in the library.

**Comment by oemertekin** [comment]
Okay, multiprocessing barely does anything. Cython might be worth having a look into.
